// =============================================================================
// The driver for the 7-segment common-anode display.
// Provides the values of some basic glyphs that can be displayed.
//
// Requires the following macros to be defined:
//
// - DISPLAY_SEGMENT_A__PIN
// - DISPLAY_SEGMENT_B__PIN
// - DISPLAY_SEGMENT_C__PIN
// - DISPLAY_SEGMENT_D__PIN
// - DISPLAY_SEGMENT_E__PIN
// - DISPLAY_SEGMENT_F__PIN
// - DISPLAY_SEGMENT_G__PIN
// - DISPLAY_SEGMENT_DP__PIN
//
// The values for the pins can be different on different platforms (boards),
// they depend on the board layout.
// =============================================================================

#ifndef __CPU__AVR__DRIVERS__DISPLAY__SEGMENT__VALUES_H
#define __CPU__AVR__DRIVERS__DISPLAY__SEGMENT__VALUES_H

#include <stdint.h>
#include "cpu/avr/gpio.h"


#define DISPLAY_SEGMENT_VALUE_EMPTY	(~0)

#define DISPLAY_SEGMENT_VALUE_0	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	))

#define DISPLAY_SEGMENT_VALUE_1	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	))

#define DISPLAY_SEGMENT_VALUE_2	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_3	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_4	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_5	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_6	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_7	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	))

#define DISPLAY_SEGMENT_VALUE_8	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_9	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_A	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_b	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_C	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	))

#define DISPLAY_SEGMENT_VALUE_d	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_E	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_F	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_H	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_P	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_n	((uint8_t)~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_MINUS	((uint8_t)~SIGNAL_MASK(DISPLAY_SEGMENT_G))

#define DISPLAY_SEGMENT_VALUE_ADD_DP(v) ((v) &= ((uint8_t)~SIGNAL_MASK(DISPLAY_SEGMENT_DP)))


#endif