// =============================================================================
// The driver for the 7-segment common-anode display.
// Provides the values of some basic glyphs that can be displayed.
//
// Requires the following macros to be defined:
//
// - DISPLAY_SEGMENT_A__PIN
// - DISPLAY_SEGMENT_B__PIN
// - DISPLAY_SEGMENT_C__PIN
// - DISPLAY_SEGMENT_D__PIN
// - DISPLAY_SEGMENT_E__PIN
// - DISPLAY_SEGMENT_F__PIN
// - DISPLAY_SEGMENT_G__PIN
// - DISPLAY_SEGMENT_DP__PIN
//
// The values for the pins can be different on different platforms (boards),
// they depend on the board layout.
// =============================================================================

#ifndef __CPU__AVR__DRIVERS__DISPLAY__SEGMENT__VALUES_H
#define __CPU__AVR__DRIVERS__DISPLAY__SEGMENT__VALUES_H

#include <stdint.h>
#include "cpu/avr/gpio.h"


#define DISPLAY_SEGMENT_VALUE_EMPTY	(~0)

#define DISPLAY_SEGMENT_VALUE_0	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	))

#define DISPLAY_SEGMENT_VALUE_1	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	))

#define DISPLAY_SEGMENT_VALUE_2	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_3	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_4	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_5	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_6	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_7	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	))

#define DISPLAY_SEGMENT_VALUE_8	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_9	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_A	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_b	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_C	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	))

#define DISPLAY_SEGMENT_VALUE_d	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_E	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_D)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_F	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_H	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_P	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_A)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_B)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_F)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_n	(~(\
    SIGNAL_MASK(DISPLAY_SEGMENT_C)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_E)	|\
    SIGNAL_MASK(DISPLAY_SEGMENT_G)	))

#define DISPLAY_SEGMENT_VALUE_MINUS	(~SIGNAL_MASK(DISPLAY_SEGMENT_G))

#define DISPLAY_SEGMENT_VALUE_ADD_DP(v) ((v) &= (~SIGNAL_MASK(DISPLAY_SEGMENT_DP)))


#endif