// =============================================================================
// The driver for the 7-segment common-anode display.
// Provides the values of some basic glyphs that can be displayed.
//
// Requires the following macros to be defined:
//
// - DISPLAY_SEGMENT_A__PIN
// - DISPLAY_SEGMENT_B__PIN
// - DISPLAY_SEGMENT_C__PIN
// - DISPLAY_SEGMENT_D__PIN
// - DISPLAY_SEGMENT_E__PIN
// - DISPLAY_SEGMENT_F__PIN
// - DISPLAY_SEGMENT_G__PIN
// - DISPLAY_SEGMENT_DP__PIN
//
// The values for the pins can be different on different platforms (boards),
// they depent on the board layout.
// =============================================================================

#ifndef __CPU__AVR__DRIVERS__DISPLAY__SEGMENT__VALUES_H
#define __CPU__AVR__DRIVERS__DISPLAY__SEGMENT__VALUES_H

#include <stdint.h>
#include <avr/sfr_defs.h>


#define DISPLAY_SEGMENT_VALUE_EMPTY	(~0)

#define DISPLAY_SEGMENT_VALUE_0	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	))

#define DISPLAY_SEGMENT_VALUE_1	(~(\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	))

#define DISPLAY_SEGMENT_VALUE_2	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_3	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_4	(~(\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_5	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_6	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_7	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	))

#define DISPLAY_SEGMENT_VALUE_8	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_9	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_A	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_b	(~(\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_C	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	))

#define DISPLAY_SEGMENT_VALUE_d	(~(\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_E	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_D__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_F	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_H	(~(\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_P	(~(\
    _BV(DISPLAY_SEGMENT_A__PIN)	|\
    _BV(DISPLAY_SEGMENT_B__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_F__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_n	(~(\
    _BV(DISPLAY_SEGMENT_C__PIN)	|\
    _BV(DISPLAY_SEGMENT_E__PIN)	|\
    _BV(DISPLAY_SEGMENT_G__PIN)	))

#define DISPLAY_SEGMENT_VALUE_MINUS	(~_BV(DISPLAY_SEGMENT_G__PIN))

#define DISPLAY_SEGMENT_VALUE_ADD_DP(v) ((v) &= (~_BV(DISPLAY_SEGMENT_DP__PIN)))

#endif